version: '3.10'
services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ".:/code"
    networks:
      - net
    container_name: auth


  postgres:
    image: "postgres"
    restart: always
    container_name: postgres
    environment:
#      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "./db_data:/var/lib/postgresql/data"
    networks:
      - net
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  net:
    driver: bridge

volumes:
  db_data: