version: '3.10'
services:
  megano:
    build:
      context: .
      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ".:/code"
    networks:
      - net
    container_name: megano

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./frontend/static/:/www/data/static/"
      - "./frontend/templates/:/www/data/templates/"
      - "./media:/www/data/media"
    networks:
      - net
    depends_on:
      - megano
    #command: ["sh", "-c", "chown -R www-data:www-data /www/data/templates/drf-yasg/swagger.json && nginx -g 'daemon off;'"]
    command: ["sh", "-c", "touch /www/data/templates/drf-yasg/swagger.json && chown -R www-data:www-data /www/data/templates/drf-yasg/swagger.json && nginx -g 'daemon off;'"]

  postgres:
    image: "postgres"
    restart: always
    container_name: postgres
    environment:
#      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "./db_data:/var/lib/postgresql/data"
    networks:
      - net
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  net:
    driver: bridge

volumes:
  db_data:
  frontend: