# Generated by Django 4.2.4 on 2023-08-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('authorized', models.BooleanField(default=False)),
                ('activation_code', models.CharField(max_length=4, null=True)),
                ('invite_code', models.CharField(blank=True, max_length=6, null=True)),
                ('referred_users', models.ManyToManyField(blank=True, to='auth_app.userprofile')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.userprofile')),
            ],
        ),
    ]
